/**
 * The shared vocabulary of the app.
 *
 * Hand-written rather than generated by shadcn's CLI. The components a
 * read-only, seven-screen app needs are a card, a badge, a table and an empty
 * state — pulling in a generator and its Radix primitives to get those would
 * be more machinery than the thing it produces. The conventions are shadcn's:
 * one component per concern, styling through class names, no theme provider.
 * See DECISIONS B-14.
 */

import type { ReactNode } from "react";

export function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

// --- Status colouring ----------------------------------------------------

/**
 * Map a status to a colour.
 *
 * Centralised because "blocked" must look the same on the board, the roadmap
 * and the dashboard — a status that is amber in one place and red in another
 * teaches the reader to distrust the colour entirely.
 */
export function statusTone(status: string | null | undefined): string {
  switch (status) {
    case "done":
    case "shipped":
    case "accepted":
    case "approved":
    case "healthy":
    case "answered":
    case "mitigated":
    case "built":
      return "text-good border-good/40 bg-good/10";
    case "blocked":
    case "down":
    case "open":
      return "text-bad border-bad/40 bg-bad/10";
    case "in_progress":
    case "active":
    case "review":
    case "degraded":
    case "draft":
      return "text-warn border-warn/40 bg-warn/10";
    case "wont_do":
    case "cut":
    case "moot":
    case "rejected":
    case "superseded":
    case "abandoned":
      return "text-ink-faint border-border-subtle bg-surface-hover line-through";
    default:
      return "text-ink-muted border-border-subtle bg-surface-hover";
  }
}

export function priorityTone(priority: string | null | undefined): string {
  switch (priority) {
    case "p0":
      return "text-bad border-bad/50 bg-bad/10 font-semibold";
    case "p1":
      return "text-warn border-warn/40 bg-warn/10";
    default:
      return "text-ink-faint border-border-subtle";
  }
}

// --- Primitives ----------------------------------------------------------

export function Badge({
  children,
  tone = "",
  title,
}: {
  children: ReactNode;
  tone?: string;
  title?: string;
}) {
  return (
    <span
      title={title}
      className={cx(
        "inline-flex items-center rounded border px-1.5 py-0.5 text-[11px] leading-none whitespace-nowrap",
        tone || "border-border-subtle text-ink-muted",
      )}
    >
      {children}
    </span>
  );
}

export function Card({
  title,
  actions,
  children,
  className,
}: {
  title?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section
      className={cx(
        "rounded-lg border border-border-subtle bg-surface-raised overflow-hidden",
        className,
      )}
    >
      {title && (
        <header className="flex items-center justify-between gap-3 border-b border-border-subtle px-4 py-2.5">
          <h2 className="text-[13px] font-semibold tracking-wide text-ink-muted uppercase">
            {title}
          </h2>
          {actions}
        </header>
      )}
      <div className="p-4">{children}</div>
    </section>
  );
}

/**
 * What to show when there is nothing.
 *
 * Takes a `hint` rather than only a message because an empty screen with no
 * explanation reads as broken. The commonest cause here is an empty store, and
 * saying so beats a shrug.
 */
export function Empty({ message, hint }: { message: string; hint?: string }) {
  return (
    <div className="py-10 text-center">
      <p className="text-ink-muted">{message}</p>
      {hint && <p className="mt-1.5 text-[13px] text-ink-faint">{hint}</p>}
    </div>
  );
}

export function Spinner({ label = "Loading…" }: { label?: string }) {
  return (
    <div className="flex items-center gap-2 py-8 text-ink-faint">
      <span className="h-3 w-3 animate-spin rounded-full border-2 border-border-subtle border-t-accent" />
      {label}
    </div>
  );
}

/**
 * An error, with what to do about it.
 *
 * The daemon being down is by far the likeliest failure and the one a human can
 * actually fix, so `ApiError` already carries that instruction and this just
 * shows it.
 */
export function ErrorBox({ error, retry }: { error: Error; retry?: () => void }) {
  return (
    <div className="rounded-lg border border-bad/40 bg-bad/10 px-4 py-3 text-[13px]">
      <p className="text-bad selectable">{error.message}</p>
      {retry && (
        <button
          onClick={retry}
          className="mt-2 rounded border border-bad/40 px-2 py-1 text-[12px] text-bad hover:bg-bad/10"
        >
          Try again
        </button>
      )}
    </div>
  );
}

/** A count with a label, for the dashboard rows. */
export function Stat({
  value,
  label,
  tone,
}: {
  value: number | string;
  label: string;
  tone?: string;
}) {
  return (
    <div className="min-w-[72px]">
      <div className={cx("text-2xl leading-none tabular-nums", tone ?? "text-ink")}>{value}</div>
      <div className="mt-1 text-[11px] tracking-wide text-ink-faint uppercase">{label}</div>
    </div>
  );
}

/** A monospace id that can be copied. */
export function Id({ value }: { value: string }) {
  return (
    <code
      className="selectable font-mono text-[11px] text-ink-faint"
      title="Click to select, then copy"
    >
      {value}
    </code>
  );
}

/**
 * Say what was left out.
 *
 * Hard constraint 4: no silent truncation. A list that was cut must say so,
 * with a total — an agent or a human shown 10 of 40 with no indication draws
 * confident wrong conclusions.
 */
export function TruncationNote({ shown, total }: { shown: number; total: number }) {
  if (shown >= total) return null;
  return (
    <p className="mt-3 text-[12px] text-ink-faint">
      Showing {shown} of {total}. Use search to find the rest.
    </p>
  );
}

/** Relative time, for feeds. */
export function when(iso: string): string {
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return iso;
  const seconds = Math.round((Date.now() - then) / 1000);
  if (seconds < 60) return "just now";
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`;
  return new Date(iso).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

/** The label an entity goes by, whatever its type calls the column. */
export function labelOf(entity: Record<string, unknown>): string {
  for (const key of ["title", "name", "term", "summary"]) {
    const value = entity[key];
    if (typeof value === "string" && value) return value;
  }
  return "(unnamed)";
}
