/**
 * The shared vocabulary of the app.
 *
 * Hand-written rather than generated by shadcn's CLI — see DECISIONS B-14. The
 * conventions are shadcn's: one component per concern, styling through class
 * names, no theme provider.
 *
 * Everything visual lives here on purpose. Before this file had primitives,
 * every clickable thing in the app declared its own appearance inline, and the
 * same filter chip had been hand-copied into six screens and had already
 * drifted apart in three of them. A primitive is not about saving keystrokes;
 * it is about there being one answer to "what does a button look like" that a
 * screen cannot quietly disagree with.
 *
 * Sizes come from the six named steps in `styles.css` (`text-display` down to
 * `text-micro`). Nothing here should carry a raw pixel size.
 */

import {
  useCallback,
  useEffect,
  useId,
  useRef,
  useState,
  type ButtonHTMLAttributes,
  type InputHTMLAttributes,
  type ReactNode,
} from "react";

export function cx(...parts: Array<string | false | null | undefined>): string {
  return parts.filter(Boolean).join(" ");
}

// --- Status colouring ----------------------------------------------------

/**
 * Map a status to a colour.
 *
 * Centralised because "blocked" must look the same on the board, the roadmap
 * and the dashboard — a status that is amber in one place and red in another
 * teaches the reader to distrust the colour entirely.
 */
export function statusTone(status: string | null | undefined): string {
  switch (status) {
    case "done":
    case "shipped":
    case "accepted":
    case "approved":
    case "healthy":
    case "answered":
    case "mitigated":
    case "built":
      return "text-good border-good/40 bg-good/10";
    case "blocked":
    case "down":
    case "open":
      return "text-bad border-bad/40 bg-bad/10";
    case "in_progress":
    case "active":
    case "review":
    case "degraded":
    case "draft":
      return "text-warn border-warn/40 bg-warn/10";
    case "wont_do":
    case "cut":
    case "moot":
    case "rejected":
    case "superseded":
    case "abandoned":
      return "text-ink-faint border-border-subtle bg-surface-hover line-through";
    default:
      return "text-ink-muted border-border-subtle bg-surface-hover";
  }
}

export function priorityTone(priority: string | null | undefined): string {
  switch (priority) {
    case "p0":
      return "text-bad border-bad/50 bg-bad/10 font-semibold";
    case "p1":
      return "text-warn border-warn/40 bg-warn/10";
    default:
      return "text-ink-faint border-border-subtle";
  }
}

// --- Interactive primitives ----------------------------------------------

/** Shared by everything focusable, so the focus ring is one decision. */
const FOCUS =
  "outline-none focus-visible:ring-2 focus-visible:ring-accent/60 focus-visible:ring-offset-1 focus-visible:ring-offset-surface";

export type ButtonVariant = "primary" | "secondary" | "ghost" | "danger";
export type ButtonSize = "sm" | "md";

const BUTTON_VARIANTS: Record<ButtonVariant, string> = {
  primary: "border-accent/60 bg-accent/15 text-accent hover:bg-accent/25",
  secondary: "border-border-subtle bg-surface-raised text-ink hover:bg-surface-hover",
  ghost: "border-transparent text-ink-muted hover:bg-surface-hover hover:text-ink",
  danger: "border-bad/40 bg-bad/10 text-bad hover:bg-bad/20",
};

const BUTTON_SIZES: Record<ButtonSize, string> = {
  sm: "px-2 py-1 text-micro",
  md: "px-2.5 py-1.5 text-small",
};

/**
 * A button.
 *
 * The app had none. Every clickable thing declared its own border, padding and
 * hover colour, which is why "refresh", "board →" and "Try again" were three
 * unrelated-looking controls doing the same kind of job.
 */
export function Button({
  variant = "secondary",
  size = "md",
  className,
  type = "button",
  ...rest
}: ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: ButtonVariant;
  size?: ButtonSize;
}) {
  return (
    <button
      type={type}
      className={cx(
        "inline-flex items-center gap-1.5 rounded border leading-none whitespace-nowrap transition-colors",
        "disabled:cursor-not-allowed disabled:opacity-40 disabled:hover:bg-transparent",
        BUTTON_VARIANTS[variant],
        BUTTON_SIZES[size],
        FOCUS,
        className,
      )}
      {...rest}
    />
  );
}

/**
 * A filter chip: a toggle that says whether it is on.
 *
 * This is the component whose six hand-copied duplicates were the clearest
 * evidence the app had no design system. The board's "urgent only", the board's
 * label chips, Search's project scope, Search's type facets, Activity's project
 * scope and Activity's actor filters were six near-identical blocks of class
 * names — and three of them had drifted, so an unselected facet was `ink-faint`
 * on one screen and `ink-muted` on another.
 */
export function Chip({
  selected = false,
  className,
  type = "button",
  ...rest
}: ButtonHTMLAttributes<HTMLButtonElement> & { selected?: boolean }) {
  return (
    <button
      type={type}
      aria-pressed={selected}
      className={cx(
        "rounded border px-2 py-1 text-micro leading-none whitespace-nowrap transition-colors",
        selected
          ? "border-accent/50 bg-accent/10 text-accent"
          : "border-border-subtle text-ink-muted hover:bg-surface-hover hover:text-ink",
        FOCUS,
        className,
      )}
      {...rest}
    />
  );
}

/** A text input. `selectable` because the global rule turns selection off. */
export function Input({
  className,
  variant = "md",
  ...rest
}: Omit<InputHTMLAttributes<HTMLInputElement>, "size"> & { variant?: "sm" | "md" | "lg" }) {
  const sizes = {
    sm: "px-2 py-1 text-small",
    md: "px-3 py-2 text-body",
    lg: "px-4 py-2.5 text-body",
  } as const;
  return (
    <input
      className={cx(
        "selectable w-full rounded-lg border border-border-subtle bg-surface-raised text-ink",
        "outline-none placeholder:text-ink-faint focus:border-accent/60",
        sizes[variant],
        className,
      )}
      {...rest}
    />
  );
}

/**
 * A modal.
 *
 * Escape is bound in the capture phase so it beats the window-level shortcut
 * handler. Without that, closing the command palette with Escape would also be
 * seen by the app's global keys, and the keypress that dismissed the dialog
 * would navigate somewhere on the way out.
 */
export function Dialog({
  open,
  onClose,
  label,
  children,
  className,
}: {
  open: boolean;
  onClose: () => void;
  label: string;
  children: ReactNode;
  className?: string;
}) {
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.preventDefault();
        e.stopPropagation();
        onClose();
      }
    };
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [open, onClose]);

  if (!open) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-start justify-center bg-black/50 px-4 pt-[12vh]"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label={label}
        className={cx(
          "w-full max-w-xl overflow-hidden rounded-xl border border-border-subtle bg-surface-raised shadow-2xl",
          className,
        )}
      >
        {children}
      </div>
    </div>
  );
}

/**
 * A dropdown menu.
 *
 * For a choice from a list long enough that laying it out as chips would be a
 * wall — the document reader's "compare with revision N" being the first case,
 * where a document with twelve revisions produced twelve chips of identical
 * weight next to twelve more.
 */
export function Menu({
  label,
  children,
  align = "left",
  size = "sm",
}: {
  label: ReactNode;
  children: (close: () => void) => ReactNode;
  align?: "left" | "right";
  size?: ButtonSize;
}) {
  const [open, setOpen] = useState(false);
  const wrap = useRef<HTMLDivElement>(null);
  const close = useCallback(() => setOpen(false), []);

  useEffect(() => {
    if (!open) return;
    const onDown = (e: MouseEvent) => {
      if (wrap.current && !wrap.current.contains(e.target as Node)) setOpen(false);
    };
    const onKey = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        e.stopPropagation();
        setOpen(false);
      }
    };
    window.addEventListener("mousedown", onDown);
    window.addEventListener("keydown", onKey, true);
    return () => {
      window.removeEventListener("mousedown", onDown);
      window.removeEventListener("keydown", onKey, true);
    };
  }, [open]);

  return (
    <div ref={wrap} className="relative inline-block">
      <Button size={size} aria-haspopup="menu" aria-expanded={open} onClick={() => setOpen((v) => !v)}>
        {label}
        <span aria-hidden className="text-ink-faint">
          ▾
        </span>
      </Button>
      {open && (
        <div
          role="menu"
          className={cx(
            "absolute z-40 mt-1 max-h-72 min-w-40 overflow-y-auto rounded-lg border border-border-subtle bg-surface-raised p-1 shadow-xl",
            align === "right" ? "right-0" : "left-0",
          )}
        >
          {children(close)}
        </div>
      )}
    </div>
  );
}

/** One row in a `Menu`. */
export function MenuItem({
  selected = false,
  className,
  type = "button",
  ...rest
}: ButtonHTMLAttributes<HTMLButtonElement> & { selected?: boolean }) {
  return (
    <button
      type={type}
      role="menuitem"
      className={cx(
        "block w-full rounded px-2 py-1.5 text-left text-small whitespace-nowrap",
        selected ? "bg-surface-hover text-ink" : "text-ink-muted hover:bg-surface-hover hover:text-ink",
        FOCUS,
        className,
      )}
      {...rest}
    />
  );
}

/**
 * A tooltip.
 *
 * Replaces the `title` attribute where the text is an explanation rather than a
 * label. The native tooltip takes about a second to appear, cannot be styled,
 * and never shows for a keyboard user — so an explanation that only exists
 * there is an explanation most readers never see.
 */
export function Tooltip({
  text,
  children,
  align = "center",
}: {
  text: string;
  children: ReactNode;
  align?: "left" | "center" | "right";
}) {
  const [shown, setShown] = useState(false);
  const id = useId();
  return (
    <span
      className="relative inline-flex"
      onMouseEnter={() => setShown(true)}
      onMouseLeave={() => setShown(false)}
      onFocus={() => setShown(true)}
      onBlur={() => setShown(false)}
      aria-describedby={shown ? id : undefined}
    >
      {children}
      {shown && (
        <span
          id={id}
          role="tooltip"
          className={cx(
            "pointer-events-none absolute bottom-full z-50 mb-1.5 w-max max-w-xs rounded-md border border-border-subtle",
            "bg-surface px-2 py-1.5 text-micro leading-snug text-ink-muted shadow-lg",
            align === "left" && "left-0",
            align === "center" && "left-1/2 -translate-x-1/2",
            align === "right" && "right-0",
          )}
        >
          {text}
        </span>
      )}
    </span>
  );
}

// --- Display primitives --------------------------------------------------

export function Badge({
  children,
  tone = "",
  title,
}: {
  children: ReactNode;
  tone?: string;
  title?: string;
}) {
  return (
    <span
      title={title}
      className={cx(
        "inline-flex items-center rounded border px-1.5 py-0.5 text-micro leading-none whitespace-nowrap",
        tone || "border-border-subtle text-ink-muted",
      )}
    >
      {children}
    </span>
  );
}

export function Card({
  title,
  actions,
  children,
  className,
}: {
  title?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
  className?: string;
}) {
  return (
    <section
      className={cx(
        "overflow-hidden rounded-lg border border-border-subtle bg-surface-raised",
        className,
      )}
    >
      {title && (
        <header className="flex items-center justify-between gap-3 border-b border-border-subtle px-4 py-2.5">
          <h2 className="text-small font-semibold tracking-wide text-ink-muted uppercase">{title}</h2>
          {actions}
        </header>
      )}
      <div className="p-4">{children}</div>
    </section>
  );
}

/**
 * What to show when there is nothing.
 *
 * Takes a `hint` rather than only a message because an empty screen with no
 * explanation reads as broken. The commonest cause here is an empty store, and
 * saying so beats a shrug.
 */
export function Empty({ message, hint }: { message: string; hint?: string }) {
  return (
    <div className="py-10 text-center">
      <p className="text-ink-muted">{message}</p>
      {hint && <p className="mt-1.5 text-small text-ink-faint">{hint}</p>}
    </div>
  );
}

export function Spinner({ label = "Loading…" }: { label?: string }) {
  return (
    <div className="flex items-center gap-2 py-8 text-ink-faint">
      <span className="h-3 w-3 animate-spin rounded-full border-2 border-border-subtle border-t-accent" />
      {label}
    </div>
  );
}

/**
 * An error, with what to do about it.
 *
 * The daemon being down is by far the likeliest failure and the one a human can
 * actually fix, so `ApiError` already carries that instruction and this just
 * shows it.
 */
export function ErrorBox({ error, retry }: { error: Error; retry?: () => void }) {
  return (
    <div className="rounded-lg border border-bad/40 bg-bad/10 px-4 py-3 text-small">
      <p className="selectable text-bad">{error.message}</p>
      {retry && (
        <Button variant="danger" size="sm" className="mt-2" onClick={retry}>
          Try again
        </Button>
      )}
    </div>
  );
}

/** A count with a label, for the dashboard rows. */
export function Stat({
  value,
  label,
  tone,
}: {
  value: number | string;
  label: string;
  tone?: string;
}) {
  return (
    <div className="min-w-[72px]">
      <div className={cx("text-display tabular-nums", tone ?? "text-ink")}>{value}</div>
      <div className="mt-1 text-micro tracking-wide text-ink-faint uppercase">{label}</div>
    </div>
  );
}

/** A monospace id that can be copied. */
export function Id({ value }: { value: string }) {
  return (
    <code
      className="selectable font-mono text-micro break-all text-ink-faint"
      title="Click to select, then copy"
    >
      {value}
    </code>
  );
}

/**
 * Say what was left out.
 *
 * Hard constraint 4: no silent truncation. A list that was cut must say so,
 * with a total — an agent or a human shown 10 of 40 with no indication draws
 * confident wrong conclusions.
 */
export function TruncationNote({ shown, total }: { shown: number; total: number }) {
  if (shown >= total) return null;
  return (
    <p className="mt-3 text-small text-ink-faint">
      Showing {shown} of {total}. Use search to find the rest.
    </p>
  );
}

/** Relative time, for feeds. */
export function when(iso: string): string {
  const then = new Date(iso).getTime();
  if (Number.isNaN(then)) return iso;
  const seconds = Math.round((Date.now() - then) / 1000);
  if (seconds < 60) return "just now";
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  if (seconds < 604800) return `${Math.floor(seconds / 86400)}d ago`;
  return new Date(iso).toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

/** The label an entity goes by, whatever its type calls the column. */
export function labelOf(entity: Record<string, unknown>): string {
  for (const key of ["title", "name", "term", "summary"]) {
    const value = entity[key];
    if (typeof value === "string" && value) return value;
  }
  return "(unnamed)";
}
