//! The closed value sets carried by entity `status`, `kind` and friends.
//!
//! Every one of these is a `TEXT` column in SQLite with no check constraint, so
//! the type system here is the only thing standing between a typo and a task
//! stuck in a status nothing queries for. `STRICT` does not help: it makes the
//! column reject a number, not an unknown string, so `in-progress` lands in it
//! as happily as `in_progress` does. They are generated by a macro so that all
//! of them produce the same shape of error — one that tells a model reading it
//! over MCP exactly which values it could have sent instead.

use crate::EntityType;

/// Declares a closed string enum with parsing, display and a `Default`.
///
/// The generated `parse` returns [`crate::Error::Invalid`] carrying the owning
/// entity type, the field name and the full list of valid values, because an
/// agent that gets "`in-progress` is not valid" without being told that
/// `in_progress` is will simply guess again.
macro_rules! string_enum {
    (
        $(#[$meta:meta])*
        $name:ident for $entity:expr, field $field:literal, default $default:ident {
            $( $(#[$vmeta:meta])* $variant:ident = $s:literal ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord,
                 serde::Serialize, serde::Deserialize)]
        pub enum $name {
            $( $(#[$vmeta])* #[serde(rename = $s)] $variant ),+
        }

        impl $name {
            /// Every value, in declaration order. Declaration order is chosen
            /// to be meaningful — statuses run from earliest to latest — so
            /// it can be used for sorting in the UI.
            pub const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            /// The stored string.
            pub const fn as_str(self) -> &'static str {
                match self { $( $name::$variant => $s ),+ }
            }

            /// Parse a stored or caller-supplied string.
            pub fn parse(s: &str) -> $crate::Result<Self> {
                match s {
                    $( $s => Ok($name::$variant), )+
                    other => Err($crate::Error::invalid(
                        $entity,
                        $field,
                        format!("`{other}` is not a recognised value"),
                        Self::options(),
                    )),
                }
            }

            /// The valid values, pipe-separated, for error messages and for
            /// the MCP tool schema's enum list.
            pub fn options() -> String {
                [ $( $s ),+ ].join(" | ")
            }
        }

        impl Default for $name {
            fn default() -> Self { $name::$default }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    };
}

string_enum! {
    /// Whether a project is being worked on.
    ProjectStatus for EntityType::Project, field "status", default Active {
        /// Active development.
        Active = "active",
        /// Deliberately on hold. Distinct from abandoned — it will come back.
        Paused = "paused",
        /// Shipped and done.
        Shipped = "shipped",
        /// Stopped and not coming back.
        Abandoned = "abandoned",
    }
}

string_enum! {
    /// Whether a milestone is a planning unit or a shipping one.
    MilestoneKind for EntityType::Milestone, field "kind", default Milestone {
        /// A planning unit.
        Milestone = "milestone",
        /// A shipping unit, which carries a version string.
        Release = "release",
    }
}

string_enum! {
    /// What has been *decided* about a milestone, which is the only part of its
    /// state a person types.
    ///
    /// Everything else — planned, active, complete, blocked — is worked out
    /// from the tasks and the edges by [`crate::MilestoneState`], and is
    /// deliberately not storable. B-57 has the argument; the short version is
    /// that five of twelve phases contradicted their own tasks and the digest
    /// spent a week naming a finished phase as the active one.
    ///
    /// This is TQ-25 applied to milestones. `blocked` was a *task* status that
    /// could disagree with the `blocks` edges, and the fix was to stop storing
    /// it rather than to check it harder.
    MilestoneStatus for EntityType::Milestone, field "status", default Open {
        /// Nothing has been declared. What the phase is doing is derived.
        Open = "open",
        /// Started, stopped, not abandoned. The one state that is real, common
        /// and impossible to derive: nobody is on it, and it is coming back.
        Paused = "paused",
        /// Delivered. Written together with `shipped_at`, never separately.
        Shipped = "shipped",
        /// Dropped from the plan. Never deleted (D-9). Replaced rather than
        /// abandoned is this plus a `supersedes` edge, the way tasks do it.
        Cut = "cut",
    }
}

/// What a phase is actually doing, worked out rather than typed.
///
/// Never stored and never accepted as input. Three of these come from counting
/// the phase's tasks, one from its edges, and the last three are whatever was
/// declared — see [`MilestoneStatus`] and B-57.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash, PartialOrd, Ord, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum MilestoneState {
    /// No task has moved off `todo`.
    ///
    /// Also the default, which is the honest answer for a phase nothing is
    /// known about: a milestone with no tasks under it derives to exactly this
    /// anyway, so the fallback and the derivation agree.
    #[default]
    Planned,
    /// A task has started and something is still open.
    Active,
    /// Something live blocks this phase. Outranks `active`, because a phase
    /// nobody can proceed on is not in flight however many tasks are open.
    Blocked,
    /// Every task closed and nobody has said what that means yet.
    ///
    /// The state `product/GATE.md` describes and the model could not hold: two
    /// of this project's phase gates cannot be verified without a human, so
    /// "the work is done" and "it shipped" are different facts.
    Complete,
    /// Set aside deliberately.
    Paused,
    /// Declared delivered.
    Shipped,
    /// Declared dropped.
    Cut,
}

impl MilestoneState {
    /// The stored string, for display and for the API.
    pub const fn as_str(self) -> &'static str {
        match self {
            MilestoneState::Planned => "planned",
            MilestoneState::Active => "active",
            MilestoneState::Blocked => "blocked",
            MilestoneState::Complete => "complete",
            MilestoneState::Paused => "paused",
            MilestoneState::Shipped => "shipped",
            MilestoneState::Cut => "cut",
        }
    }

    /// Whether this phase still wants work doing.
    ///
    /// `complete` is not open: the tasks are finished and what is left is a
    /// decision rather than work. That distinction is the whole reason
    /// `complete` exists.
    pub const fn wants_work(self) -> bool {
        matches!(
            self,
            MilestoneState::Planned | MilestoneState::Active | MilestoneState::Blocked
        )
    }
}

/// How a phase's live tasks are distributed, which is three of the four inputs
/// to [`MilestoneState::derive`].
///
/// A struct rather than three `usize` parameters because
/// `derive(declared, 4, 0, 2, false)` at a call site says nothing about which
/// number is which, and getting two of them the wrong way round produces a
/// plausible state rather than an error.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct TaskTally {
    /// Every live task in the phase.
    pub total: usize,
    /// Closed, by either reason. `done` and `wont_do` both land here, which is
    /// exactly why neither can imply `shipped` — see B-57.
    pub closed: usize,
    /// Open and picked up: anything not `todo` and not closed.
    pub started: usize,
}

/// Where a phase has actually got to, as opposed to what its column says.
///
/// The three facts the roadmap needs to answer "is this moving, and how far
/// through is it" without anyone having typed a date. They travel together
/// because they come out of the same pair of queries and every caller wants
/// all three: the digest, the tracker, and the API behind the roadmap screen.
///
/// This replaces a bare [`MilestoneState`], which was the derived half of the
/// answer with the counts it was derived *from* thrown away — so the app
/// recounted them in the browser and `render_status` recounted them again.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct MilestoneProgress {
    /// What the phase is doing, worked out from the rest.
    pub state: MilestoneState,
    /// How its live tasks are distributed.
    pub tally: TaskTally,
    /// When anything under it last moved, from the event log.
    ///
    /// `None` means nothing has ever happened to one of its tasks, which for a
    /// release row is the normal case rather than a gap — releases carry no
    /// tasks. Read it with the tally beside it, not alone.
    pub last_activity: Option<chrono::DateTime<chrono::Utc>>,
}

impl MilestoneState {
    /// Work out a phase's state from what was declared and what its tasks say.
    ///
    /// A declaration always wins, because it is the part a person actually
    /// decided and no amount of counting tasks can second-guess it. A phase
    /// that shipped with a straggler is still shipped — Phase 8 is exactly
    /// that, which is why "shipped must have no open tasks" would be wrong.
    pub fn derive(declared: MilestoneStatus, tally: TaskTally, blocked: bool) -> Self {
        match declared {
            MilestoneStatus::Shipped => return MilestoneState::Shipped,
            MilestoneStatus::Cut => return MilestoneState::Cut,
            MilestoneStatus::Paused => return MilestoneState::Paused,
            MilestoneStatus::Open => {}
        }
        // Blocked outranks active: a phase nothing can proceed on is not in
        // flight, however many of its tasks are open.
        if blocked {
            return MilestoneState::Blocked;
        }
        // Named but never scoped. Phase 10 is this, except that it has no
        // milestone at all — a workflow gap B-57 leaves open.
        if tally.total == 0 {
            return MilestoneState::Planned;
        }
        if tally.closed == tally.total {
            return MilestoneState::Complete;
        }
        if tally.started > 0 || tally.closed > 0 {
            MilestoneState::Active
        } else {
            MilestoneState::Planned
        }
    }
}

string_enum! {
    /// What sort of work a task represents.
    TaskKind for EntityType::Task, field "kind", default Task {
        /// Ordinary work.
        Task = "task",
        /// Something broken.
        Bug = "bug",
        /// Maintenance with no user-visible effect.
        Chore = "chore",
        /// Time-boxed investigation whose output is knowledge, not code.
        Spike = "spike",
    }
}

string_enum! {
    /// Where a task stands.
    ///
    /// There is deliberately no `blocked`. Being blocked is a fact about the
    /// *graph* — something links to this task with `blocks` — and holding it as
    /// a status too meant two facts that had to agree and did not. Two tasks
    /// were marked blocked with nothing linked to them at the moment the
    /// decision was taken. Derived, the contradiction cannot be written down.
    TaskStatus for EntityType::Task, field "status", default Todo {
        /// Not started.
        Todo = "todo",
        /// Being worked on.
        InProgress = "in_progress",
        /// Work is complete and awaiting confirmation. This is where a merged
        /// PR lands (D-8) — proposed, never auto-closed.
        Review = "review",
        /// Finished.
        Done = "done",
        /// Deliberately not doing it.
        WontDo = "wont_do",
    }
}

impl TaskStatus {
    /// Whether a task in this status still needs attention.
    ///
    /// Used by `specline_context`'s "attention" section and by the blocker
    /// traversal, both of which should ignore work that is finished or
    /// abandoned.
    pub const fn is_open(self) -> bool {
        !matches!(self, TaskStatus::Done | TaskStatus::WontDo)
    }

    /// Whether reaching this status means the task has stopped.
    ///
    /// The inverse of [`is_open`](Self::is_open), named separately because the
    /// write path asks the question in this direction: every route into a
    /// terminal status owes a reason, a message and — for `done` — evidence,
    /// and the store had spelled the same `matches!` out by hand at each one.
    /// Two hand-written copies of a rule are two chances for it to differ, and
    /// the create path differing from the update path is what KEEL-217 was.
    pub const fn is_terminal(self) -> bool {
        !self.is_open()
    }
}

string_enum! {
    /// Why a task stopped being open.
    ///
    /// Five reasons over two terminal statuses, which is the whole point of the
    /// column existing. `done` maps to [`TaskStatus::Done`]; the other four all
    /// map to [`TaskStatus::WontDo`], because "not doing it", "already done
    /// elsewhere", "the plan changed" and "nothing needed doing" are four
    /// different things that a single status cannot tell apart. Adding four
    /// statuses instead was the alternative, and it would have put the same
    /// information somewhere every query filtering on `is_open` has to learn
    /// about.
    ///
    /// The default is `Done` only because the macro requires one. Nothing reads
    /// it — the reason is an argument of the close, never inferred.
    CloseReason for EntityType::Task, field "close_reason", default Done {
        /// Finished. Needs a message and at least one piece of evidence.
        Done = "done",
        /// Deliberately not doing it. Needs a message.
        WontDo = "wont_do",
        /// The same work as another task, which keeps the history.
        Duplicate = "duplicate",
        /// Replaced by another task that says it better.
        Superseded = "superseded",
        /// Looked at it, and there was nothing to do.
        NoChange = "no_change",
    }
}

impl CloseReason {
    /// The status a task lands in when closed for this reason.
    pub const fn status(self) -> TaskStatus {
        match self {
            CloseReason::Done => TaskStatus::Done,
            _ => TaskStatus::WontDo,
        }
    }

    /// Whether this reason names another task, and therefore draws an edge.
    ///
    /// `duplicate` writes `duplicates` and `superseded` writes `supersedes`.
    /// Both relations already exist, so the automatic link needs no schema —
    /// and drawing it here is what stops "closed as a duplicate of what?"
    /// being a question only the message can answer.
    pub const fn relation(self) -> Option<crate::Relation> {
        match self {
            CloseReason::Duplicate => Some(crate::Relation::Duplicates),
            CloseReason::Superseded => Some(crate::Relation::Supersedes),
            _ => None,
        }
    }

    /// Whether closing for this reason demands evidence.
    ///
    /// Only `done` does. A task nobody did has nothing to show, and demanding
    /// a commit for "we decided not to" would teach people to invent one.
    pub const fn needs_evidence(self) -> bool {
        matches!(self, CloseReason::Done)
    }
}

string_enum! {
    /// How urgent a task is.
    TaskPriority for EntityType::Task, field "priority", default P2 {
        /// Drop everything.
        P0 = "p0",
        /// Next.
        P1 = "p1",
        /// Normal.
        P2 = "p2",
        /// Someday.
        P3 = "p3",
    }
}

impl TaskPriority {
    /// Whether this priority is surfaced in `specline_context`'s attention list.
    pub const fn is_urgent(self) -> bool {
        matches!(self, TaskPriority::P0 | TaskPriority::P1)
    }
}

string_enum! {
    /// What sort of prose document a spec is.
    SpecKind for EntityType::Spec, field "kind", default Spec {
        /// Product requirements.
        Prd = "prd",
        /// Technical specification.
        Spec = "spec",
        /// A proposal seeking comment.
        Rfc = "rfc",
        /// A design document.
        DesignDoc = "design-doc",
        /// One idea that survived triage, and why it is worth building.
        ///
        /// A feature is a spec rather than a task because the thinking
        /// outlives the work: it exists whether or not the thing is ever
        /// built, and it is what a session picking up child task nine reads to
        /// understand why the other eight matter. The unit of work is a
        /// separate epic task created at the moment somebody decides to build,
        /// which is what keeps unbuilt ideas off the board entirely (B-90).
        Feature = "feature",
        /// Anything else worth keeping as prose.
        Note = "note",
    }
}

string_enum! {
    /// How settled a spec is.
    SpecStatus for EntityType::Spec, field "status", default Draft {
        /// Being written.
        Draft = "draft",
        /// Awaiting sign-off.
        Review = "review",
        /// Agreed.
        Approved = "approved",
        /// Replaced by a newer document, which should carry a `supersedes`
        /// edge to this one.
        Superseded = "superseded",
    }
}

string_enum! {
    /// How settled a decision is.
    DecisionStatus for EntityType::Decision, field "status", default Proposed {
        /// Written down but not agreed.
        Proposed = "proposed",
        /// Agreed. Editing one is allowed and recorded: a decision that was
        /// wrong is marked `Superseded` with a `## Superseded` section, but a
        /// decision whose *title was truncated at import* is a transcription
        /// defect and correcting it is not an amendment. The revision chain
        /// tells the two apart after the fact; a write guard could not tell
        /// them apart at all (TQ-27, B-43).
        Accepted = "accepted",
        /// Replaced by a later decision.
        Superseded = "superseded",
        /// Considered and declined. Kept because knowing what was rejected is
        /// as useful as knowing what was chosen.
        Rejected = "rejected",
    }
}

string_enum! {
    /// Whether an unknown is a question, a risk or an assumption.
    QuestionKind for EntityType::Question, field "kind", default Question {
        /// Something not yet known.
        Question = "question",
        /// Something that might go wrong.
        Risk = "risk",
        /// Something being taken as true without proof.
        Assumption = "assumption",
    }
}

string_enum! {
    /// Where an unknown stands.
    QuestionStatus for EntityType::Question, field "status", default Open {
        /// Still unresolved.
        Open = "open",
        /// Resolved with an answer.
        Answered = "answered",
        /// Acknowledged and consciously carried rather than resolved.
        Accepted = "accepted",
        /// A risk whose likelihood or impact has been reduced.
        Mitigated = "mitigated",
        /// No longer relevant.
        Moot = "moot",
    }
}

impl QuestionStatus {
    /// Whether this item still belongs in `specline_context`'s never-truncated
    /// open-questions list.
    ///
    /// SPEC §6.3 declares questions unbounded because a *missing* open
    /// question makes an agent actively do the wrong thing — re-litigating a
    /// settled decision. Resolved ones carry no such risk, so they drop out.
    pub const fn is_unresolved(self) -> bool {
        matches!(self, QuestionStatus::Open)
    }
}

string_enum! {
    /// How bad a risk is.
    RiskSeverity for EntityType::Question, field "severity", default Medium {
        /// Tolerable.
        Low = "low",
        /// Worth watching.
        Medium = "medium",
        /// Needs a mitigation now.
        High = "high",
    }
}

string_enum! {
    /// Where a piece of feedback came from.
    FeedbackKind for EntityType::Feedback, field "kind", default Observation {
        /// A user interview.
        Interview = "interview",
        /// A support conversation.
        Support = "support",
        /// A sales conversation.
        Sales = "sales",
        /// An unprompted idea.
        Idea = "idea",
        /// Something a competitor did.
        Competitor = "competitor",
        /// Something noticed rather than told.
        Observation = "observation",
    }
}

string_enum! {
    /// How the source felt.
    Sentiment for EntityType::Feedback, field "sentiment", default Neutral {
        /// Happy.
        Positive = "positive",
        /// Neither.
        Neutral = "neutral",
        /// Unhappy.
        Negative = "negative",
        /// Both, which is usually the most informative kind.
        Mixed = "mixed",
    }
}

string_enum! {
    /// How far along a design artifact is.
    DesignState for EntityType::Design, field "state", default Proposed {
        /// Suggested.
        Proposed = "proposed",
        /// Agreed but not built.
        Approved = "approved",
        /// What actually shipped. UC-5 shows this beside the proposal.
        Built = "built",
    }
}

string_enum! {
    /// Whether a deployment target is healthy.
    EnvironmentStatus for EntityType::Environment, field "status", default Unknown {
        /// Working.
        Healthy = "healthy",
        /// Working badly.
        Degraded = "degraded",
        /// Not working.
        Down = "down",
        /// Nobody has said. The honest default — Specline does not probe
        /// environments (Q-6).
        Unknown = "unknown",
    }
}

string_enum! {
    /// Which way is good for a metric.
    MetricDirection for EntityType::Metric, field "direction", default Up {
        /// Higher is better.
        Up = "up",
        /// Lower is better.
        Down = "down",
    }
}

string_enum! {
    /// What sort of thing a generic artifact is.
    ArtifactKind for EntityType::Artifact, field "kind", default Link {
        /// A URL.
        Link = "link",
        /// A file.
        File = "file",
        /// An image.
        Image = "image",
        /// Anything else.
        Other = "other",
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    /// Every closed set must round-trip and must reject nonsense with a
    /// message naming the alternatives. Written once as a macro-driven sweep
    /// so a new enum cannot be added without inheriting the check.
    macro_rules! check {
        ($($t:ty),+ $(,)?) => {$(
            for v in <$t>::ALL {
                assert_eq!(<$t>::parse(v.as_str()).unwrap(), *v);
            }
            let err = <$t>::parse("definitely-not-a-value").unwrap_err().to_string();
            assert!(
                err.contains("definitely-not-a-value"),
                "{} should quote the bad value: {err}", stringify!($t)
            );
            let first = <$t>::ALL[0].as_str();
            assert!(
                err.contains(first),
                "{} should list valid options: {err}", stringify!($t)
            );
            assert!(
                <$t>::ALL.contains(&<$t>::default()),
                "{} default must be one of its own values", stringify!($t)
            );
        )+};
    }

    #[test]
    fn every_closed_set_round_trips_and_explains_itself() {
        check!(
            ProjectStatus,
            MilestoneKind,
            MilestoneStatus,
            TaskKind,
            TaskStatus,
            TaskPriority,
            SpecKind,
            SpecStatus,
            DecisionStatus,
            QuestionKind,
            QuestionStatus,
            RiskSeverity,
            FeedbackKind,
            Sentiment,
            DesignState,
            EnvironmentStatus,
            MetricDirection,
            ArtifactKind,
        );
    }

    #[test]
    fn open_task_statuses_exclude_finished_work() {
        assert!(TaskStatus::Todo.is_open());
        assert!(TaskStatus::InProgress.is_open());
        assert!(
            TaskStatus::Review.is_open(),
            "review still needs confirming"
        );
        assert!(!TaskStatus::Done.is_open());
        assert!(!TaskStatus::WontDo.is_open());
    }

    #[test]
    fn only_open_questions_count_as_unresolved() {
        assert!(QuestionStatus::Open.is_unresolved());
        for s in [
            QuestionStatus::Answered,
            QuestionStatus::Accepted,
            QuestionStatus::Mitigated,
            QuestionStatus::Moot,
        ] {
            assert!(!s.is_unresolved(), "{s} should not be unresolved");
        }
    }

    #[test]
    fn urgent_priorities_are_p0_and_p1_only() {
        assert!(TaskPriority::P0.is_urgent());
        assert!(TaskPriority::P1.is_urgent());
        assert!(!TaskPriority::P2.is_urgent());
        assert!(!TaskPriority::P3.is_urgent());
    }

    #[test]
    fn hyphenated_spec_kind_is_preserved() {
        // `design-doc` is the one value with a hyphen. A well-meaning
        // rename_all would turn it into `design_doc` and silently orphan
        // every existing row.
        assert_eq!(SpecKind::DesignDoc.as_str(), "design-doc");
        assert_eq!(SpecKind::parse("design-doc").unwrap(), SpecKind::DesignDoc);
        assert!(SpecKind::parse("design_doc").is_err());
    }

    #[test]
    fn serde_uses_the_stored_string() {
        let json = serde_json::to_string(&TaskStatus::InProgress).unwrap();
        assert_eq!(json, "\"in_progress\"");
        let back: TaskStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(back, TaskStatus::InProgress);
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod milestone_state_tests {
    use super::*;

    /// `total`, `closed`, `started` — in that order, which is the order the
    /// struct declares them and the reason it is a struct.
    fn tally(total: usize, closed: usize, started: usize) -> TaskTally {
        TaskTally {
            total,
            closed,
            started,
        }
    }

    fn derive(declared: MilestoneStatus, t: TaskTally) -> MilestoneState {
        MilestoneState::derive(declared, t, false)
    }

    /// A declaration is the last word. No count of tasks can overrule it,
    /// because no count can tell you what a person decided.
    ///
    /// Phase 8 is the case that matters: shipped, with one task still open.
    /// A rule of "shipped must have no open tasks" would call that a mistake,
    /// and it is not one.
    #[test]
    fn a_declaration_beats_whatever_the_tasks_say() {
        for declared in [
            MilestoneStatus::Shipped,
            MilestoneStatus::Cut,
            MilestoneStatus::Paused,
        ] {
            for t in [
                tally(0, 0, 0),
                tally(5, 0, 0),
                tally(5, 4, 1),
                tally(5, 5, 0),
            ] {
                let state = derive(declared, t);
                assert_eq!(
                    state.as_str(),
                    declared.as_str(),
                    "{declared:?} with {t:?} should stay {declared:?}"
                );
            }
        }
    }

    /// And a declaration outranks being blocked, for the same reason: a phase
    /// somebody has cut is cut, whatever is still linked to it.
    #[test]
    fn a_declaration_beats_being_blocked_too() {
        assert_eq!(
            MilestoneState::derive(MilestoneStatus::Cut, tally(3, 0, 1), true),
            MilestoneState::Cut
        );
    }

    #[test]
    fn nothing_started_is_planned() {
        assert_eq!(
            derive(MilestoneStatus::Open, tally(4, 0, 0)),
            MilestoneState::Planned
        );
    }

    /// A phase named and never scoped. Not an error — it is where a phase sits
    /// between being decided on and being broken into work.
    #[test]
    fn no_tasks_at_all_is_planned() {
        assert_eq!(
            derive(MilestoneStatus::Open, tally(0, 0, 0)),
            MilestoneState::Planned
        );
    }

    /// Started counts whether the movement was into progress or into done.
    /// Either way somebody has touched it.
    #[test]
    fn work_begun_with_work_left_is_active() {
        assert_eq!(
            derive(MilestoneStatus::Open, tally(4, 0, 1)),
            MilestoneState::Active,
            "a task in progress is work begun"
        );
        assert_eq!(
            derive(MilestoneStatus::Open, tally(4, 2, 0)),
            MilestoneState::Active,
            "so is a task already closed, even with nothing in progress now"
        );
    }

    /// The state the model could not hold, and the reason `complete` exists:
    /// `product/GATE.md` says two of this project's phase gates cannot be
    /// verified without a human, so "the work is finished" and "it shipped"
    /// are different facts. Phases 7 and 9 sat here unnoticed.
    #[test]
    fn every_task_closed_and_undeclared_is_complete() {
        assert_eq!(
            derive(MilestoneStatus::Open, tally(8, 8, 0)),
            MilestoneState::Complete
        );
    }

    /// Complete is reached by *any* closure, including abandonment — which is
    /// exactly why it is not `shipped`. A phase whose every task was closed
    /// `wont_do` has finished and delivered nothing, and only a person can say
    /// which of shipped or cut that is.
    #[test]
    fn complete_says_nothing_about_whether_anything_was_delivered() {
        // The tally cannot tell `done` from `wont_do`, and deliberately so:
        // if it could, something would eventually be tempted to guess.
        assert_eq!(
            derive(MilestoneStatus::Open, tally(1, 1, 0)),
            MilestoneState::Complete,
            "one abandoned task is still a phase with no work left in it"
        );
    }

    /// Blocked outranks active: a phase nothing can proceed on is not in
    /// flight, however many of its tasks are open.
    #[test]
    fn blocked_outranks_active_but_not_complete() {
        assert_eq!(
            MilestoneState::derive(MilestoneStatus::Open, tally(4, 1, 1), true),
            MilestoneState::Blocked
        );
        assert_eq!(
            MilestoneState::derive(MilestoneStatus::Open, tally(4, 0, 0), true),
            MilestoneState::Blocked,
            "a phase blocked before it starts is blocked, not planned"
        );
    }

    /// What still wants doing. `complete` is not open work — the tasks are
    /// finished and what is left is a decision.
    #[test]
    fn only_unfinished_states_want_work() {
        for (state, wants) in [
            (MilestoneState::Planned, true),
            (MilestoneState::Active, true),
            (MilestoneState::Blocked, true),
            (MilestoneState::Complete, false),
            (MilestoneState::Paused, false),
            (MilestoneState::Shipped, false),
            (MilestoneState::Cut, false),
        ] {
            assert_eq!(state.wants_work(), wants, "{state:?}");
        }
    }

    /// Every state renders as the word the roadmap prints. A missing arm here
    /// is a phase that displays as something nobody chose.
    #[test]
    fn every_state_has_a_word() {
        for (state, word) in [
            (MilestoneState::Planned, "planned"),
            (MilestoneState::Active, "active"),
            (MilestoneState::Blocked, "blocked"),
            (MilestoneState::Complete, "complete"),
            (MilestoneState::Paused, "paused"),
            (MilestoneState::Shipped, "shipped"),
            (MilestoneState::Cut, "cut"),
        ] {
            assert_eq!(state.as_str(), word);
        }
    }

    /// The four words that are no longer storable. If one of these ever parses
    /// again, migration 3 and the write guard have both been undone.
    #[test]
    fn the_derived_words_cannot_be_parsed_as_a_declaration() {
        for word in ["planned", "active", "blocked", "complete"] {
            assert!(
                MilestoneStatus::parse(word).is_err(),
                "`{word}` is derived and must not be storable"
            );
        }
        for word in ["open", "paused", "shipped", "cut"] {
            assert!(
                MilestoneStatus::parse(word).is_ok(),
                "`{word}` is a declaration"
            );
        }
    }
}
