//! The closed value sets carried by entity `status`, `kind` and friends.
//!
//! Every one of these is a `VARCHAR` in DuckDB with no check constraint, so
//! the type system here is the only thing standing between a typo and a task
//! stuck in a status nothing queries for. They are generated by a macro so
//! that all of them produce the same shape of error — one that tells a model
//! reading it over MCP exactly which values it could have sent instead.

use crate::EntityType;

/// Declares a closed string enum with parsing, display and a `Default`.
///
/// The generated `parse` returns [`crate::Error::Invalid`] carrying the owning
/// entity type, the field name and the full list of valid values, because an
/// agent that gets "`in-progress` is not valid" without being told that
/// `in_progress` is will simply guess again.
macro_rules! string_enum {
    (
        $(#[$meta:meta])*
        $name:ident for $entity:expr, field $field:literal, default $default:ident {
            $( $(#[$vmeta:meta])* $variant:ident = $s:literal ),+ $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord,
                 serde::Serialize, serde::Deserialize)]
        pub enum $name {
            $( $(#[$vmeta])* #[serde(rename = $s)] $variant ),+
        }

        impl $name {
            /// Every value, in declaration order. Declaration order is chosen
            /// to be meaningful — statuses run from earliest to latest — so
            /// it can be used for sorting in the UI.
            pub const ALL: &'static [$name] = &[ $( $name::$variant ),+ ];

            /// The stored string.
            pub const fn as_str(self) -> &'static str {
                match self { $( $name::$variant => $s ),+ }
            }

            /// Parse a stored or caller-supplied string.
            pub fn parse(s: &str) -> $crate::Result<Self> {
                match s {
                    $( $s => Ok($name::$variant), )+
                    other => Err($crate::Error::invalid(
                        $entity,
                        $field,
                        format!("`{other}` is not a recognised value"),
                        Self::options(),
                    )),
                }
            }

            /// The valid values, pipe-separated, for error messages and for
            /// the MCP tool schema's enum list.
            pub fn options() -> String {
                [ $( $s ),+ ].join(" | ")
            }
        }

        impl Default for $name {
            fn default() -> Self { $name::$default }
        }

        impl std::fmt::Display for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.as_str())
            }
        }
    };
}

string_enum! {
    /// Whether a project is being worked on.
    ProjectStatus for EntityType::Project, field "status", default Active {
        /// Active development.
        Active = "active",
        /// Deliberately on hold. Distinct from abandoned — it will come back.
        Paused = "paused",
        /// Shipped and done.
        Shipped = "shipped",
        /// Stopped and not coming back.
        Abandoned = "abandoned",
    }
}

string_enum! {
    /// Whether a milestone is a planning unit or a shipping one.
    MilestoneKind for EntityType::Milestone, field "kind", default Milestone {
        /// A planning unit.
        Milestone = "milestone",
        /// A shipping unit, which carries a version string.
        Release = "release",
    }
}

string_enum! {
    /// Where a milestone stands.
    MilestoneStatus for EntityType::Milestone, field "status", default Planned {
        /// Not started.
        Planned = "planned",
        /// In flight.
        Active = "active",
        /// Held up by something else.
        Blocked = "blocked",
        /// Delivered.
        Shipped = "shipped",
        /// Dropped from the plan. Never deleted (D-9).
        Cut = "cut",
    }
}

string_enum! {
    /// What sort of work a task represents.
    TaskKind for EntityType::Task, field "kind", default Task {
        /// Ordinary work.
        Task = "task",
        /// Something broken.
        Bug = "bug",
        /// Maintenance with no user-visible effect.
        Chore = "chore",
        /// Time-boxed investigation whose output is knowledge, not code.
        Spike = "spike",
    }
}

string_enum! {
    /// Where a task stands.
    TaskStatus for EntityType::Task, field "status", default Todo {
        /// Not started.
        Todo = "todo",
        /// Being worked on.
        InProgress = "in_progress",
        /// Held up. The blocker should be a `blocks` edge, not just prose.
        Blocked = "blocked",
        /// Work is complete and awaiting confirmation. This is where a merged
        /// PR lands (D-8) — proposed, never auto-closed.
        Review = "review",
        /// Finished.
        Done = "done",
        /// Deliberately not doing it.
        WontDo = "wont_do",
    }
}

impl TaskStatus {
    /// Whether a task in this status still needs attention.
    ///
    /// Used by `keel_context`'s "attention" section and by the blocker
    /// traversal, both of which should ignore work that is finished or
    /// abandoned.
    pub const fn is_open(self) -> bool {
        !matches!(self, TaskStatus::Done | TaskStatus::WontDo)
    }
}

string_enum! {
    /// How urgent a task is.
    TaskPriority for EntityType::Task, field "priority", default P2 {
        /// Drop everything.
        P0 = "p0",
        /// Next.
        P1 = "p1",
        /// Normal.
        P2 = "p2",
        /// Someday.
        P3 = "p3",
    }
}

impl TaskPriority {
    /// Whether this priority is surfaced in `keel_context`'s attention list.
    pub const fn is_urgent(self) -> bool {
        matches!(self, TaskPriority::P0 | TaskPriority::P1)
    }
}

string_enum! {
    /// What sort of prose document a spec is.
    SpecKind for EntityType::Spec, field "kind", default Spec {
        /// Product requirements.
        Prd = "prd",
        /// Technical specification.
        Spec = "spec",
        /// A proposal seeking comment.
        Rfc = "rfc",
        /// A design document.
        DesignDoc = "design-doc",
        /// Anything else worth keeping as prose.
        Note = "note",
    }
}

string_enum! {
    /// How settled a spec is.
    SpecStatus for EntityType::Spec, field "status", default Draft {
        /// Being written.
        Draft = "draft",
        /// Awaiting sign-off.
        Review = "review",
        /// Agreed.
        Approved = "approved",
        /// Replaced by a newer document, which should carry a `supersedes`
        /// edge to this one.
        Superseded = "superseded",
    }
}

string_enum! {
    /// How settled a decision is.
    DecisionStatus for EntityType::Decision, field "status", default Proposed {
        /// Written down but not agreed.
        Proposed = "proposed",
        /// Agreed. Content becomes immutable at this point — supersede
        /// instead of editing.
        Accepted = "accepted",
        /// Replaced by a later decision.
        Superseded = "superseded",
        /// Considered and declined. Kept because knowing what was rejected is
        /// as useful as knowing what was chosen.
        Rejected = "rejected",
    }
}

string_enum! {
    /// Whether an unknown is a question, a risk or an assumption.
    QuestionKind for EntityType::Question, field "kind", default Question {
        /// Something not yet known.
        Question = "question",
        /// Something that might go wrong.
        Risk = "risk",
        /// Something being taken as true without proof.
        Assumption = "assumption",
    }
}

string_enum! {
    /// Where an unknown stands.
    QuestionStatus for EntityType::Question, field "status", default Open {
        /// Still unresolved.
        Open = "open",
        /// Resolved with an answer.
        Answered = "answered",
        /// Acknowledged and consciously carried rather than resolved.
        Accepted = "accepted",
        /// A risk whose likelihood or impact has been reduced.
        Mitigated = "mitigated",
        /// No longer relevant.
        Moot = "moot",
    }
}

impl QuestionStatus {
    /// Whether this item still belongs in `keel_context`'s never-truncated
    /// open-questions list.
    ///
    /// SPEC §6.3 declares questions unbounded because a *missing* open
    /// question makes an agent actively do the wrong thing — re-litigating a
    /// settled decision. Resolved ones carry no such risk, so they drop out.
    pub const fn is_unresolved(self) -> bool {
        matches!(self, QuestionStatus::Open)
    }
}

string_enum! {
    /// How bad a risk is.
    RiskSeverity for EntityType::Question, field "severity", default Medium {
        /// Tolerable.
        Low = "low",
        /// Worth watching.
        Medium = "medium",
        /// Needs a mitigation now.
        High = "high",
    }
}

string_enum! {
    /// Where a piece of feedback came from.
    FeedbackKind for EntityType::Feedback, field "kind", default Observation {
        /// A user interview.
        Interview = "interview",
        /// A support conversation.
        Support = "support",
        /// A sales conversation.
        Sales = "sales",
        /// An unprompted idea.
        Idea = "idea",
        /// Something a competitor did.
        Competitor = "competitor",
        /// Something noticed rather than told.
        Observation = "observation",
    }
}

string_enum! {
    /// How the source felt.
    Sentiment for EntityType::Feedback, field "sentiment", default Neutral {
        /// Happy.
        Positive = "positive",
        /// Neither.
        Neutral = "neutral",
        /// Unhappy.
        Negative = "negative",
        /// Both, which is usually the most informative kind.
        Mixed = "mixed",
    }
}

string_enum! {
    /// How far along a design artifact is.
    DesignState for EntityType::Design, field "state", default Proposed {
        /// Suggested.
        Proposed = "proposed",
        /// Agreed but not built.
        Approved = "approved",
        /// What actually shipped. UC-5 shows this beside the proposal.
        Built = "built",
    }
}

string_enum! {
    /// Whether a deployment target is healthy.
    EnvironmentStatus for EntityType::Environment, field "status", default Unknown {
        /// Working.
        Healthy = "healthy",
        /// Working badly.
        Degraded = "degraded",
        /// Not working.
        Down = "down",
        /// Nobody has said. The honest default — Keel does not probe
        /// environments (Q-6).
        Unknown = "unknown",
    }
}

string_enum! {
    /// Which way is good for a metric.
    MetricDirection for EntityType::Metric, field "direction", default Up {
        /// Higher is better.
        Up = "up",
        /// Lower is better.
        Down = "down",
    }
}

string_enum! {
    /// What sort of thing a generic artifact is.
    ArtifactKind for EntityType::Artifact, field "kind", default Link {
        /// A URL.
        Link = "link",
        /// A file.
        File = "file",
        /// An image.
        Image = "image",
        /// Anything else.
        Other = "other",
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;

    /// Every closed set must round-trip and must reject nonsense with a
    /// message naming the alternatives. Written once as a macro-driven sweep
    /// so a new enum cannot be added without inheriting the check.
    macro_rules! check {
        ($($t:ty),+ $(,)?) => {$(
            for v in <$t>::ALL {
                assert_eq!(<$t>::parse(v.as_str()).unwrap(), *v);
            }
            let err = <$t>::parse("definitely-not-a-value").unwrap_err().to_string();
            assert!(
                err.contains("definitely-not-a-value"),
                "{} should quote the bad value: {err}", stringify!($t)
            );
            let first = <$t>::ALL[0].as_str();
            assert!(
                err.contains(first),
                "{} should list valid options: {err}", stringify!($t)
            );
            assert!(
                <$t>::ALL.contains(&<$t>::default()),
                "{} default must be one of its own values", stringify!($t)
            );
        )+};
    }

    #[test]
    fn every_closed_set_round_trips_and_explains_itself() {
        check!(
            ProjectStatus,
            MilestoneKind,
            MilestoneStatus,
            TaskKind,
            TaskStatus,
            TaskPriority,
            SpecKind,
            SpecStatus,
            DecisionStatus,
            QuestionKind,
            QuestionStatus,
            RiskSeverity,
            FeedbackKind,
            Sentiment,
            DesignState,
            EnvironmentStatus,
            MetricDirection,
            ArtifactKind,
        );
    }

    #[test]
    fn open_task_statuses_exclude_finished_work() {
        assert!(TaskStatus::Todo.is_open());
        assert!(TaskStatus::InProgress.is_open());
        assert!(TaskStatus::Blocked.is_open());
        assert!(
            TaskStatus::Review.is_open(),
            "review still needs confirming"
        );
        assert!(!TaskStatus::Done.is_open());
        assert!(!TaskStatus::WontDo.is_open());
    }

    #[test]
    fn only_open_questions_count_as_unresolved() {
        assert!(QuestionStatus::Open.is_unresolved());
        for s in [
            QuestionStatus::Answered,
            QuestionStatus::Accepted,
            QuestionStatus::Mitigated,
            QuestionStatus::Moot,
        ] {
            assert!(!s.is_unresolved(), "{s} should not be unresolved");
        }
    }

    #[test]
    fn urgent_priorities_are_p0_and_p1_only() {
        assert!(TaskPriority::P0.is_urgent());
        assert!(TaskPriority::P1.is_urgent());
        assert!(!TaskPriority::P2.is_urgent());
        assert!(!TaskPriority::P3.is_urgent());
    }

    #[test]
    fn hyphenated_spec_kind_is_preserved() {
        // `design-doc` is the one value with a hyphen. A well-meaning
        // rename_all would turn it into `design_doc` and silently orphan
        // every existing row.
        assert_eq!(SpecKind::DesignDoc.as_str(), "design-doc");
        assert_eq!(SpecKind::parse("design-doc").unwrap(), SpecKind::DesignDoc);
        assert!(SpecKind::parse("design_doc").is_err());
    }

    #[test]
    fn serde_uses_the_stored_string() {
        let json = serde_json::to_string(&TaskStatus::InProgress).unwrap();
        assert_eq!(json, "\"in_progress\"");
        let back: TaskStatus = serde_json::from_str(&json).unwrap();
        assert_eq!(back, TaskStatus::InProgress);
    }
}
