//! The tracker renderer — `product/STATUS.md` and its equivalents.
//!
//! The dogfooding switch. `product/STATUS.md` has been the tracker since before
//! there was anything to track with; once Keel holds the project, that file
//! should be generated from it rather than hand-maintained, or the two drift
//! and the hand-written one wins by default.
//!
//! This is **not** the §8 markdown mirror, and the difference is worth being
//! precise about. The mirror is prose-only (TQ-5) — specs, decisions, open
//! questions, glossary — because tasks churn too much and would make repo diffs
//! noisy. A status file is exactly the churny, task-shaped thing the mirror
//! deliberately excludes, so it needs its own renderer. The handoff called this
//! out and asked for it as a Phase 1 task.
//!
//! Like the mirror, output is one-directional: this file is generated, never
//! read back.

use crate::{
    Cursor, DuckStore, Entity, EntityId, EntityQuery, EntityStore, EntityType, Error,
    MilestoneStatus, Note, Result, TaskStatus,
};
use std::fmt::Write as _;

/// Render a tracker for one project.
pub fn render(store: &DuckStore, project_id: &EntityId) -> Result<String> {
    let Some(Entity::Project(project)) = store.get(project_id)? else {
        return Err(Error::NotFound {
            entity_type: EntityType::Project,
            id: project_id.to_string(),
        });
    };

    let mut out = String::new();
    let now = chrono::Utc::now();

    writeln!(out, "# {} — Status", project.name)?;
    writeln!(out)?;
    writeln!(
        out,
        "<!-- keel:generated project {} {} -->",
        project.id,
        now.format("%Y-%m-%dT%H:%M:%SZ")
    )?;
    writeln!(
        out,
        "> **Generated by `keel render-status`. Do not edit — Keel is the source of truth.**"
    )?;
    writeln!(out)?;

    // --- At a glance -----------------------------------------------------
    let tasks = collect(store, project_id, EntityType::Task)?;
    // Every stream in one call. Fifty tasks asking one at a time is fifty round
    // trips to answer one question.
    let all_notes = store.notes_in_project(project_id)?;
    let notes: Vec<&Note> = all_notes.iter().collect();
    let milestones = collect(store, project_id, EntityType::Milestone)?;
    let questions = collect(store, project_id, EntityType::Question)?;

    let open: Vec<&Entity> = tasks
        .iter()
        .filter(|t| matches!(t, Entity::Task(t) if t.status.is_open()))
        .collect();
    // The one derivation, shared with the digest and the app. Counting a
    // `blocked` status here is what let this file and the ranking state
    // different numbers about the same project.
    let blocked_ids = crate::next::blocked_tasks(store, project_id)?;
    let blocked = blocked_ids.len();
    let urgent = open
        .iter()
        .filter(|t| matches!(t, Entity::Task(t) if t.priority.is_urgent()))
        .count();
    let active_milestone = milestones
        .iter()
        .find(|m| matches!(m, Entity::Milestone(m) if m.status == MilestoneStatus::Active));
    let unresolved = questions
        .iter()
        .filter(|q| matches!(q, Entity::Question(q) if q.status.is_unresolved()))
        .count();

    writeln!(out, "## At a glance")?;
    writeln!(out)?;
    writeln!(out, "| | |")?;
    writeln!(out, "|---|---|")?;
    writeln!(out, "| **Status** | {} |", project.status)?;
    // The project's own word, not Keel's. This one says "Phase" on every screen
    // and the tracker said "milestone" anyway, so the vocabulary in the committed
    // shadow of the board was the store's rather than the project's (KEEL-121).
    let noun = project.milestone_word();
    writeln!(
        out,
        "| **Active {}** | {} |",
        noun.to_lowercase(),
        active_milestone.map_or("none".to_owned(), |m| m.label().to_owned())
    )?;
    writeln!(
        out,
        "| **Open work** | {} task(s), {urgent} urgent, {blocked} blocked |",
        open.len()
    )?;
    writeln!(out, "| **Open questions** | {unresolved} |")?;
    // No "Generated at" row. The banner above carries the timestamp, and the
    // banner is the one thing `generate --check` excludes from comparison —
    // precisely so that regenerating an unchanged project is not a diff. A
    // timestamp in the table body would defeat that and make `--check` fail
    // whenever a run straddled a minute boundary: a red CI that means nothing,
    // which is worse than no check at all.
    writeln!(out)?;

    // --- Milestones ------------------------------------------------------
    if !milestones.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## {}", plural(noun))?;
        writeln!(out)?;
        writeln!(out, "| {noun} | Status | Target | Tasks done |")?;
        writeln!(out, "|---|---|---|---|")?;

        let mut sorted: Vec<&Entity> = milestones.iter().collect();
        sorted.sort_by_key(|m| match m {
            Entity::Milestone(m) => (m.sort_order.unwrap_or(i32::MAX), m.name.clone()),
            _ => (i32::MAX, String::new()),
        });

        for m in sorted {
            let Entity::Milestone(milestone) = m else {
                continue;
            };
            let under: Vec<&Entity> = tasks
                .iter()
                .filter(|t| matches!(t, Entity::Task(t) if t.milestone_id.as_ref() == Some(&milestone.id)))
                .collect();
            let done = under
                .iter()
                .filter(|t| matches!(t, Entity::Task(t) if !t.status.is_open()))
                .count();
            writeln!(
                out,
                "| {} | `{}` | {} | {done} / {} |",
                milestone.name,
                milestone.status,
                milestone
                    .target_date
                    .map_or("—".to_owned(), |d| d.to_string()),
                under.len()
            )?;
        }
        writeln!(out)?;
    }

    // --- What to do next --------------------------------------------------
    //
    // The best computation in the system, and until now it appeared everywhere
    // except the file a human opens. A tracker whose first question is "what
    // should I pick up" should answer it before listing ninety-three rows.
    let next = crate::next::rank(store, project_id)?;
    if !next.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## What's next")?;
        writeln!(out)?;
        if next.ready.is_empty() {
            writeln!(
                out,
                "Nothing is ready to pick up — everything open is blocked or waiting on a \
                 decision, so unblocking one of the below is the work."
            )?;
            writeln!(out)?;
        }
        for item in next.ready.iter().take(5) {
            writeln!(
                out,
                "- **{}** {} — {}",
                item.reference, item.title, item.why
            )?;
        }
        if !next.waiting_on_you.is_empty() {
            writeln!(out)?;
            writeln!(out, "**Waiting on a decision**")?;
            writeln!(out)?;
            for item in &next.waiting_on_you {
                writeln!(out, "- **{}** {}", item.reference, item.title)?;
            }
        }
        if !next.blocked.is_empty() {
            writeln!(out)?;
            writeln!(out, "**Blocked**")?;
            writeln!(out)?;
            for item in &next.blocked {
                writeln!(
                    out,
                    "- **{}** {} — {}",
                    item.reference, item.title, item.why
                )?;
            }
        }
        writeln!(out)?;
    }

    // --- Tasks -----------------------------------------------------------
    writeln!(out, "---")?;
    writeln!(out)?;
    writeln!(out, "## Tasks")?;
    writeln!(out)?;

    // Grouped by status in lifecycle order, so the file reads like a board
    // rather than an id dump — with blocked work pulled out first, because it
    // is derived from the edges rather than being one of the statuses.
    let blocked_group: Vec<&Entity> = tasks
        .iter()
        .filter(|t| matches!(t, Entity::Task(t) if blocked_ids.contains(&t.id)))
        .collect();

    for status in std::iter::once(None).chain(TaskStatus::ALL.iter().map(Some)) {
        let group: Vec<&Entity> = match status {
            None => blocked_group.clone(),
            Some(status) => tasks
                .iter()
                .filter(|t| {
                    matches!(t, Entity::Task(t) if t.status == *status
                        && !blocked_ids.contains(&t.id))
                })
                .collect(),
        };
        if group.is_empty() {
            continue;
        }
        let heading = match status {
            None => "blocked".to_owned(),
            Some(status) => status.to_string(),
        };
        writeln!(out, "### {heading} ({})", group.len())?;
        writeln!(out)?;
        for t in group {
            let Entity::Task(task) = t else { continue };
            // The readable identifier, not the ULID. This file is read by a
            // human, and a wall of `tsk_01KZKW28CS4Q1WSB0D95B2A01G` is most of
            // why it stopped being worth opening.
            let mut line = format!(
                "- **{}-{}** {} `{}`",
                project.key, task.number, task.title, task.priority
            );
            if !task.labels.is_empty() {
                line.push_str(&format!(" · {}", task.labels.join(", ")));
            }
            for (i, url) in task.external_refs.iter().enumerate() {
                line.push_str(&format!(" · [link {}]({url})", i + 1));
            }
            writeln!(out, "{line}")?;

            // The task's own description, then the running commentary. This is
            // what made the tracker worth reading when it was prose, and its
            // absence is the entire reason the prose version outlived the rows.
            let body = task
                .body
                .as_deref()
                .map(str::trim)
                .filter(|b| !b.is_empty());
            let stream: Vec<&&Note> = notes.iter().filter(|n| n.entity_id == task.id).collect();

            if let Some(body) = body {
                writeln!(out)?;
                for para in body.lines() {
                    writeln!(out, "  {para}")?;
                }
            }
            if !stream.is_empty() {
                writeln!(out)?;
                for note in stream {
                    // Attribution inline rather than in its own column: a note
                    // is read for its content, and "who and when" is the
                    // footnote that makes it checkable, not the headline.
                    writeln!(
                        out,
                        "  - {} <sub>— {} · {}</sub>",
                        note.body.replace('\n', " ").trim(),
                        note.author,
                        note.created_at.format("%Y-%m-%d")
                    )?;
                }
                writeln!(out)?;
            } else if body.is_some() {
                writeln!(out)?;
            }
        }
        writeln!(out)?;
    }

    // --- Open questions --------------------------------------------------
    let open_questions: Vec<&Entity> = questions
        .iter()
        .filter(|q| matches!(q, Entity::Question(q) if q.status.is_unresolved()))
        .collect();
    if !open_questions.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Open questions and risks")?;
        writeln!(out)?;
        writeln!(out, "| Question | Kind | Severity |")?;
        writeln!(out, "|---|---|---|")?;
        for q in open_questions {
            let Entity::Question(question) = q else {
                continue;
            };
            writeln!(
                out,
                "| {} | {} | {} |",
                question.title,
                question.kind,
                question.severity.map_or("—".to_owned(), |s| s.to_string())
            )?;
        }
        writeln!(out)?;
    }

    // --- Decisions -------------------------------------------------------
    let decisions = collect(store, project_id, EntityType::Decision)?;
    if !decisions.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Decisions")?;
        writeln!(out)?;
        for d in &decisions {
            let Entity::Decision(decision) = d else {
                continue;
            };
            writeln!(
                out,
                "- **{}** — `{}`{}",
                decision.title,
                decision.status,
                decision
                    .decided_at
                    .map_or(String::new(), |t| format!(", {}", t.format("%Y-%m-%d")))
            )?;
        }
        writeln!(out)?;
    }

    // --- Changelog -------------------------------------------------------
    // Derived from the event log rather than hand-written, which is the whole
    // point: the log already knows what happened and who did it.
    let events = store.events(&Cursor::Beginning, Some(project_id), 5_000)?;
    if !events.items.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Changelog")?;
        writeln!(out)?;
        writeln!(out, "| Date | Actor | Change |")?;
        writeln!(out, "|---|---|---|")?;
        // Newest first, and capped — but the cap is stated, never silent.
        let shown = 40.min(events.items.len());
        for e in events.items.iter().rev().take(shown) {
            writeln!(
                out,
                "| {} | {} | {} |",
                e.created_at.format("%Y-%m-%d"),
                e.actor,
                e.summary.replace('|', "\\|")
            )?;
        }
        writeln!(out)?;
        if events.items.len() > shown {
            writeln!(
                out,
                "*Showing the {shown} most recent of {} changes. Use `keel_activity` for the rest.*",
                events.items.len()
            )?;
            writeln!(out)?;
        }
    }

    Ok(out)
}

/// Every live entity of one type in a project.
/// A heading for more than one of something.
///
/// English enough for the words a project actually uses — Phase, Cycle, Release,
/// Milestone, Sprint. Not a general pluraliser and not trying to be: a project
/// whose noun ends awkwardly gets a slightly wrong heading, which is a smaller
/// cost than a dependency or a table of irregulars nobody maintains.
fn plural(noun: &str) -> String {
    let lower = noun.to_lowercase();
    if lower.ends_with('s')
        || lower.ends_with("ch")
        || lower.ends_with("sh")
        || lower.ends_with('x')
    {
        return format!("{noun}es");
    }
    if lower.ends_with('y') && !lower.ends_with("ay") && !lower.ends_with("ey") {
        return format!("{}ies", &noun[..noun.len() - 1]);
    }
    format!("{noun}s")
}

fn collect(
    store: &DuckStore,
    project_id: &EntityId,
    entity_type: EntityType,
) -> Result<Vec<Entity>> {
    Ok(store
        .list(
            &EntityQuery::in_project(project_id.clone())
                .of_type(entity_type)
                .limited(5_000),
        )?
        .items)
}
