//! The tracker renderer — `product/STATUS.md` and its equivalents.
//!
//! The dogfooding switch. `product/STATUS.md` has been the tracker since before
//! there was anything to track with; once Keel holds the project, that file
//! should be generated from it rather than hand-maintained, or the two drift
//! and the hand-written one wins by default.
//!
//! This is **not** the §8 markdown mirror, and the difference is worth being
//! precise about. The mirror is prose-only (TQ-5) — specs, decisions, open
//! questions, glossary — because tasks churn too much and would make repo diffs
//! noisy. A status file is exactly the churny, task-shaped thing the mirror
//! deliberately excludes, so it needs its own renderer. The handoff called this
//! out and asked for it as a Phase 1 task.
//!
//! Like the mirror, output is one-directional: this file is generated, never
//! read back.

use crate::{
    Cursor, DuckStore, Entity, EntityId, EntityQuery, EntityStore, EntityType, Error,
    MilestoneStatus, Result, TaskStatus,
};
use std::fmt::Write as _;

/// Render a tracker for one project.
pub fn render(store: &DuckStore, project_id: &EntityId) -> Result<String> {
    let Some(Entity::Project(project)) = store.get(project_id)? else {
        return Err(Error::NotFound {
            entity_type: EntityType::Project,
            id: project_id.to_string(),
        });
    };

    let mut out = String::new();
    let now = chrono::Utc::now();

    writeln!(out, "# {} — Status", project.name)?;
    writeln!(out)?;
    writeln!(
        out,
        "<!-- keel:generated project {} {} -->",
        project.id,
        now.format("%Y-%m-%dT%H:%M:%SZ")
    )?;
    writeln!(
        out,
        "> **Generated by `keel render-status`. Do not edit — Keel is the source of truth.**"
    )?;
    writeln!(out)?;

    // --- At a glance -----------------------------------------------------
    let tasks = collect(store, project_id, EntityType::Task)?;
    let milestones = collect(store, project_id, EntityType::Milestone)?;
    let questions = collect(store, project_id, EntityType::Question)?;

    let open: Vec<&Entity> = tasks
        .iter()
        .filter(|t| matches!(t, Entity::Task(t) if t.status.is_open()))
        .collect();
    let blocked = open
        .iter()
        .filter(|t| matches!(t, Entity::Task(t) if t.status == TaskStatus::Blocked))
        .count();
    let urgent = open
        .iter()
        .filter(|t| matches!(t, Entity::Task(t) if t.priority.is_urgent()))
        .count();
    let active_milestone = milestones
        .iter()
        .find(|m| matches!(m, Entity::Milestone(m) if m.status == MilestoneStatus::Active));
    let unresolved = questions
        .iter()
        .filter(|q| matches!(q, Entity::Question(q) if q.status.is_unresolved()))
        .count();

    writeln!(out, "## At a glance")?;
    writeln!(out)?;
    writeln!(out, "| | |")?;
    writeln!(out, "|---|---|")?;
    writeln!(out, "| **Status** | {} |", project.status)?;
    writeln!(
        out,
        "| **Active milestone** | {} |",
        active_milestone.map_or("none".to_owned(), |m| m.label().to_owned())
    )?;
    writeln!(
        out,
        "| **Open work** | {} task(s), {urgent} urgent, {blocked} blocked |",
        open.len()
    )?;
    writeln!(out, "| **Open questions** | {unresolved} |")?;
    writeln!(
        out,
        "| **Generated** | {} |",
        now.format("%Y-%m-%d %H:%M UTC")
    )?;
    writeln!(out)?;

    // --- Milestones ------------------------------------------------------
    if !milestones.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Milestones")?;
        writeln!(out)?;
        writeln!(out, "| Milestone | Status | Target | Tasks done |")?;
        writeln!(out, "|---|---|---|---|")?;

        let mut sorted: Vec<&Entity> = milestones.iter().collect();
        sorted.sort_by_key(|m| match m {
            Entity::Milestone(m) => (m.sort_order.unwrap_or(i32::MAX), m.name.clone()),
            _ => (i32::MAX, String::new()),
        });

        for m in sorted {
            let Entity::Milestone(milestone) = m else {
                continue;
            };
            let under: Vec<&Entity> = tasks
                .iter()
                .filter(|t| matches!(t, Entity::Task(t) if t.milestone_id.as_ref() == Some(&milestone.id)))
                .collect();
            let done = under
                .iter()
                .filter(|t| matches!(t, Entity::Task(t) if !t.status.is_open()))
                .count();
            writeln!(
                out,
                "| {} | `{}` | {} | {done} / {} |",
                milestone.name,
                milestone.status,
                milestone
                    .target_date
                    .map_or("—".to_owned(), |d| d.to_string()),
                under.len()
            )?;
        }
        writeln!(out)?;
    }

    // --- Tasks -----------------------------------------------------------
    writeln!(out, "---")?;
    writeln!(out)?;
    writeln!(out, "## Tasks")?;
    writeln!(out)?;

    // Grouped by status in lifecycle order, so the file reads like a board
    // rather than an id dump.
    for status in TaskStatus::ALL {
        let group: Vec<&Entity> = tasks
            .iter()
            .filter(|t| matches!(t, Entity::Task(t) if t.status == *status))
            .collect();
        if group.is_empty() {
            continue;
        }
        writeln!(out, "### {status} ({})", group.len())?;
        writeln!(out)?;
        for t in group {
            let Entity::Task(task) = t else { continue };
            let mut line = format!("- **{}** `{}`", task.title, task.priority);
            if !task.labels.is_empty() {
                line.push_str(&format!(" · {}", task.labels.join(", ")));
            }
            if let Some(url) = &task.external_ref {
                line.push_str(&format!(" · [PR]({url})"));
            }
            line.push_str(&format!(" · `{}`", task.id));
            writeln!(out, "{line}")?;
        }
        writeln!(out)?;
    }

    // --- Open questions --------------------------------------------------
    let open_questions: Vec<&Entity> = questions
        .iter()
        .filter(|q| matches!(q, Entity::Question(q) if q.status.is_unresolved()))
        .collect();
    if !open_questions.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Open questions and risks")?;
        writeln!(out)?;
        writeln!(out, "| Question | Kind | Severity |")?;
        writeln!(out, "|---|---|---|")?;
        for q in open_questions {
            let Entity::Question(question) = q else {
                continue;
            };
            writeln!(
                out,
                "| {} | {} | {} |",
                question.title,
                question.kind,
                question.severity.map_or("—".to_owned(), |s| s.to_string())
            )?;
        }
        writeln!(out)?;
    }

    // --- Decisions -------------------------------------------------------
    let decisions = collect(store, project_id, EntityType::Decision)?;
    if !decisions.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Decisions")?;
        writeln!(out)?;
        for d in &decisions {
            let Entity::Decision(decision) = d else {
                continue;
            };
            writeln!(
                out,
                "- **{}** — `{}`{}",
                decision.title,
                decision.status,
                decision
                    .decided_at
                    .map_or(String::new(), |t| format!(", {}", t.format("%Y-%m-%d")))
            )?;
        }
        writeln!(out)?;
    }

    // --- Changelog -------------------------------------------------------
    // Derived from the event log rather than hand-written, which is the whole
    // point: the log already knows what happened and who did it.
    let events = store.events(&Cursor::Beginning, Some(project_id), 5_000)?;
    if !events.items.is_empty() {
        writeln!(out, "---")?;
        writeln!(out)?;
        writeln!(out, "## Changelog")?;
        writeln!(out)?;
        writeln!(out, "| Date | Actor | Change |")?;
        writeln!(out, "|---|---|---|")?;
        // Newest first, and capped — but the cap is stated, never silent.
        let shown = 40.min(events.items.len());
        for e in events.items.iter().rev().take(shown) {
            writeln!(
                out,
                "| {} | {} | {} |",
                e.created_at.format("%Y-%m-%d"),
                e.actor,
                e.summary.replace('|', "\\|")
            )?;
        }
        writeln!(out)?;
        if events.items.len() > shown {
            writeln!(
                out,
                "*Showing the {shown} most recent of {} changes. Use `keel_activity` for the rest.*",
                events.items.len()
            )?;
            writeln!(out)?;
        }
    }

    Ok(out)
}

/// Every live entity of one type in a project.
fn collect(
    store: &DuckStore,
    project_id: &EntityId,
    entity_type: EntityType,
) -> Result<Vec<Entity>> {
    Ok(store
        .list(
            &EntityQuery::in_project(project_id.clone())
                .of_type(entity_type)
                .limited(5_000),
        )?
        .items)
}
